In [ ]:
import numpy as np
import statistics as st

In [ ]:
data = [12, 15, 21, 21, 18, 19, 25, 30, 30, 28, 29, 40, 12, 18, 25]

In [ ]:
# Mean Result
mean = np.mean(data)
print(mean)


22.866666666666667


In [ ]:
# Median Result
median = np.median(data)
print(median)


21.0


In [ ]:
# Mode Result
mode = st.mode(data)
print(mode)

12


In [ ]:
# Variance
variance = np.var(data)
print(variance)

55.71555555555556


In [ ]:
#Standard Result
standard_result = np.std(data)
print(standardresult)

7.464285334548483


In [ ]:
Height = [45, 67, 23, 67, 89, 34, 56, 67, 89, 12, 90, 45, 67, 34, 56, 78, 23, 45, 67, 89, 12]


In [ ]:
# Variance
variance = np.var(Height)
print(variance)

55.71555555555556


In [ ]:
#Standard Deviation
standard_result = np.std(Height)
print(standardresult)

7.464285334548483


In [ ]:
#10th percentile.
percentile_10th = np.percentile(Height, 10)
print(percentile_10th)


23.0


In [ ]:
#25th percentile.
percentile_25th = np.percentile(Height, 25)
print(percentile_25th)

34.0


In [ ]:
#50th percentile.
percentile_50th = np.percentile(Height, 50)
print(percentile_50th)

56.0


In [ ]:
#75th percentile.
percentile_75th = np.percentile(Height, 75)
print(percentile_75th)

67.0


In [ ]:
# ADDITION, SUBSTRACTION AND MULTIPLICATION OF MATRIX

In [ ]:
matrix_A = np.array([[4, 1, 6], [1, 9, 3], [7, 1, 8], [4, 5, 9]])

matrix_B = np.array([[5, 3, 7], [6, 5, 8], [2, 1, 9], [6, 2, 4]])

matrix_C = np.array([[4, 9, 6], [9, 3, 5], [4, 6, 7], [4, 8, 5]])

print(matrix_A + matrix_B + matrix_C)


[[13 13 19]
 [16 17 16]
 [13  8 24]
 [14 15 18]]


In [ ]:
print(matrix_A - matrix_B - matrix_C)


[[ -5 -11  -7]
 [-14   1 -10]
 [  1  -6  -8]
 [ -6  -5   0]]


In [ ]:
print(matrix_A * matrix_B * matrix_C)


[[ 80  27 252]
 [ 54 135 120]
 [ 56   6 504]
 [ 96  80 180]]


In [ ]:
9+(matrix_A)

array([[13, 10, 15],
       [10, 18, 12],
       [16, 10, 17],
       [13, 14, 18]])

In [ ]:
print(matrix_A)

[[4 1 6]
 [1 9 3]
 [7 1 8]
 [4 5 9]]


In [ ]:
9-(matrix_A)

array([[5, 8, 3],
       [8, 0, 6],
       [2, 8, 1],
       [5, 4, 0]])

In [ ]:
9*(matrix_A)

array([[36,  9, 54],
       [ 9, 81, 27],
       [63,  9, 72],
       [36, 45, 81]])

In [ ]:
10+(matrix_A + matrix_B + matrix_C)

array([[23, 23, 29],
       [26, 27, 26],
       [23, 18, 34],
       [24, 25, 28]])

In [ ]:
# TRANSPOSE OF MATRIX (Flipping)

In [ ]:
print(matrix_A.T)

[[4 1 7 4]
 [1 9 1 5]
 [6 3 8 9]]


In [ ]:
trans = np.transpose(matrix_A)
print(trans)

[[4 1 7 4]
 [1 9 1 5]
 [6 3 8 9]]


In [ ]:
#flat_matrixA = matrix_A.flatten()

#print(flat_matrixA)

#mode = st.mode(flat_matrixA)
#print(mode)

In [ ]:
# EXERCISE

In [ ]:
# QUestion 1

matrix_F = np.array([[4, 1, 6], [1, 9, 3]])

print(matrix_F)

[[4 1 6]
 [1 9 3]]


In [ ]:
# Question 2

matrix_G = np.array([[2, 8, 5], [2, 6, 7]])

print(matrix_G)

[[2 8 5]
 [2 6 7]]


In [ ]:
# Question 3

print(matrix_F + matrix_G)


[[ 6  9 11]
 [ 3 15 10]]


In [ ]:
# Question 4

print(matrix_F - matrix_G)

[[ 2 -7  1]
 [-1  3 -4]]


In [ ]:
# Question 5

print(matrix_F.T)

[[4 1]
 [1 9]
 [6 3]]


In [ ]:
# Question 6

5*(matrix_F)

array([[20,  5, 30],
       [ 5, 45, 15]])